import { 
  UserProfile, 
  BankAccount, 
  Beneficiary, 
  PaymentTransaction, 
  OfferOrReward, 
  AdminSystemMetrics 
} from '@auto-upi/shared';
import { v4 as uuidv4 } from 'uuid';

export class InMemoryDatabase {
  public currentUser: UserProfile = {
    id: 'usr_auto_889210',
    name: 'Aarav Patel',
    email: 'aarav.patel@example.com',
    phone: '+1 (555) 234-8901',
    upiId: 'aarav@autoupi',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'USER',
    kycStatus: 'TIER_2_VERIFIED',
    kycTier: 2,
    dailyLimitUsd: 25000,
    remainingDailyLimitUsd: 21850,
    country: 'United States',
    defaultCurrency: 'USD',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
  };

  public bankAccounts: BankAccount[] = [
    {
      id: 'acc_sbi_inr_01',
      userId: 'usr_auto_889210',
      bankName: 'State Bank of India',
      accountNumberMasked: '•••• 6492',
      routingOrIfsc: 'SBIN0006492',
      accountType: 'SAVINGS',
      currency: 'INR',
      balance: 684520.00,
      isPrimary: true,
      isReserveBacked: true,
      status: 'ACTIVE',
    },
    {
      id: 'acc_hdfc_inr_02',
      userId: 'usr_auto_889210',
      bankName: 'HDFC Bank',
      accountNumberMasked: '•••• 7712',
      routingOrIfsc: 'HDFC0000128',
      accountType: 'SAVINGS',
      currency: 'INR',
      balance: 845210.00,
      isPrimary: false,
      isReserveBacked: true,
      status: 'ACTIVE',
    },
    {
      id: 'acc_union_inr_03',
      userId: 'usr_auto_889210',
      bankName: 'Union Bank of India',
      accountNumberMasked: '•••• 3891',
      routingOrIfsc: 'UBIN0533891',
      accountType: 'SAVINGS',
      currency: 'INR',
      balance: 562800.00,
      isPrimary: false,
      isReserveBacked: true,
      status: 'ACTIVE',
    },
    {
      id: 'acc_kotak_inr_04',
      userId: 'usr_auto_889210',
      bankName: 'Kotak Mahindra Bank',
      accountNumberMasked: '•••• 9045',
      routingOrIfsc: 'KKBK0000904',
      accountType: 'SAVINGS',
      currency: 'INR',
      balance: 729150.00,
      isPrimary: false,
      isReserveBacked: true,
      status: 'ACTIVE',
    }
  ];


  public beneficiaries: Beneficiary[] = [
    {
      id: 'ben_priya_in',
      userId: 'usr_auto_889210',
      name: 'Priya Sharma',
      upiIdOrHandle: 'priya.sharma@okaxis',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      initials: 'PS',
      country: 'India',
      countryCode: 'IN',
      flagEmoji: '🇮🇳',
      currency: 'INR',
      bankName: 'State Bank of India',
      accountNumberMasked: '•••• 3819',
      routingIdentifier: 'SBIN0004829',
      phoneOrEmail: '+91 98765 43210',
      verificationState: 'VERIFIED',
      isFavorite: true,
      lastTransferDate: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'ben_alex_gb',
      userId: 'usr_auto_889210',
      name: 'Alex Johnson',
      upiIdOrHandle: 'alex.j@payuk',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      initials: 'AJ',
      country: 'United Kingdom',
      countryCode: 'GB',
      flagEmoji: '🇬🇧',
      currency: 'GBP',
      bankName: 'Barclays Bank',
      accountNumberMasked: '•••• 8820',
      routingIdentifier: '20-04-15',
      phoneOrEmail: 'alex.johnson@payuk.co.uk',
      verificationState: 'VERIFIED',
      isFavorite: true,
      lastTransferDate: new Date(Date.now() - 7 * 86400000).toISOString(),
    },
    {
      id: 'ben_wei_sg',
      userId: 'usr_auto_889210',
      name: 'Wei Chen',
      upiIdOrHandle: 'wei.chen@paynow',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      initials: 'WC',
      country: 'Singapore',
      countryCode: 'SG',
      flagEmoji: '🇸🇬',
      currency: 'SGD',
      bankName: 'DBS Bank Singapore',
      accountNumberMasked: '•••• 6621',
      routingIdentifier: 'DBSSSGSG',
      phoneOrEmail: '+65 9123 4567',
      verificationState: 'VERIFIED',
      isFavorite: true,
      lastTransferDate: new Date(Date.now() - 14 * 86400000).toISOString(),
    },
    {
      id: 'ben_mateo_eu',
      userId: 'usr_auto_889210',
      name: 'Mateo Silva',
      upiIdOrHandle: 'mateo.s@sepa',
      avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
      initials: 'MS',
      country: 'Germany',
      countryCode: 'DE',
      flagEmoji: '🇪🇺',
      currency: 'EUR',
      bankName: 'BNP Paribas',
      accountNumberMasked: '•••• 1044',
      routingIdentifier: 'DEUTDEFFXXX',
      phoneOrEmail: 'mateo.silva@sepa.de',
      verificationState: 'VERIFIED',
      isFavorite: false,
    },
    {
      id: 'ben_kenji_jp',
      userId: 'usr_auto_889210',
      name: 'Kenji Sato',
      upiIdOrHandle: 'kenji.sato@zengin',
      avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      initials: 'KS',
      country: 'Japan',
      countryCode: 'JP',
      flagEmoji: '🇯🇵',
      currency: 'JPY',
      bankName: 'MUFG Bank Tokyo',
      accountNumberMasked: '•••• 5529',
      routingIdentifier: 'BOTKJPJT',
      phoneOrEmail: 'kenji.sato@zengin.jp',
      verificationState: 'VERIFIED',
      isFavorite: false,
    }
  ];

  public offersAndRewards: OfferOrReward[] = [
    {
      id: 'rew_cb_01',
      type: 'CASHBACK',
      title: 'Zero-Fee Transfer Milestone',
      description: 'You earned 100% FX fee rebate on your next corridor transfer over $200',
      amountOrPercent: '$15.00 FX Rebate',
      expiresAt: new Date(Date.now() + 15 * 86400000).toISOString(),
      isUnlocked: true,
      code: 'ZEROXB2026',
      bgGradient: 'from-blue-600/30 to-indigo-600/30 border-blue-500/30'
    },
    {
      id: 'rew_scratch_02',
      type: 'SCRATCH_CARD',
      title: 'Global Corridors Mystery Reward',
      description: 'Tap to scratch & unlock bonus settlement token yield',
      amountOrPercent: 'Up to ₹1,500',
      expiresAt: new Date(Date.now() + 5 * 86400000).toISOString(),
      isUnlocked: false,
      bgGradient: 'from-violet-600/30 to-fuchsia-600/30 border-violet-500/30'
    },
    {
      id: 'rew_disc_03',
      type: 'FX_DISCOUNT',
      title: 'SG PayNow Corridor Boost',
      description: 'Get +0.45% above interbank mid-market rate on SGD conversion',
      amountOrPercent: '+0.45% FX Boost',
      expiresAt: new Date(Date.now() + 30 * 86400000).toISOString(),
      isUnlocked: true,
      code: 'SGBOOST',
      bgGradient: 'from-emerald-600/30 to-teal-600/30 border-emerald-500/30'
    }
  ];

  public transactions: PaymentTransaction[] = [
    {
      id: 'tx_upi_992810',
      referenceNumber: 'UPI-XB-8921820',
      userId: 'usr_auto_889210',
      beneficiaryId: 'ben_priya_in',
      beneficiaryName: 'Priya Sharma',
      beneficiaryUpiId: 'priya.sharma@okaxis',
      beneficiaryCountry: 'India',
      beneficiaryFlag: '🇮🇳',
      senderBankAccountId: 'acc_chase_usd_01',
      senderBankName: 'JPMorgan Chase Bank',
      senderUpiId: 'aarav@autoupi',
      sourceCurrency: 'USD',
      sourceAmount: 350.00,
      targetCurrency: 'INR',
      targetAmount: 29225.00,
      exchangeRate: 83.50,
      fee: 1.50,
      feeCurrency: 'USD',
      status: 'RECIPIENT_CREDITED',
      purpose: 'FAMILY_SUPPORT',
      note: 'Birthday gift & family expenses',
      timeline: [
        {
          step: 'INITIATED',
          title: 'Payment Initiated',
          description: 'Payment authorized via 2FA OTP verification',
          timestamp: new Date(Date.now() - 3600000 * 24).toISOString(),
          isCompleted: true,
          isCurrent: false,
          isFailed: false,
        },
        {
          step: 'FX_LOCKED',
          title: 'FX Rate Guaranteed',
          description: 'Locked 1 USD = 83.50 INR with zero spread slippage',
          timestamp: new Date(Date.now() - 3600000 * 24 + 1000).toISOString(),
          isCompleted: true,
          isCurrent: false,
          isFailed: false,
        },
        {
          step: 'RESERVE_LOCKED',
          title: 'Bank Reserve Escrow Locked',
          description: 'USD 350.00 locked in JPMorgan Chase custody vault',
          timestamp: new Date(Date.now() - 3600000 * 24 + 2000).toISOString(),
          isCompleted: true,
          isCurrent: false,
          isFailed: false,
        },
        {
          step: 'TOKEN_MINTED',
          title: 'Settlement Token Minted',
          description: '350.00 AUST minted on Auto-UPI EVM Testnet',
          timestamp: new Date(Date.now() - 3600000 * 24 + 3200).toISOString(),
          isCompleted: true,
          isCurrent: false,
          isFailed: false,
          txHash: '0x8f2a947c61d5639e4bf37f90c883e015d9a927c3d18e27c191a84f39b6e82a91'
        },
        {
          step: 'BLOCKCHAIN_SETTLED',
          title: 'EVM Testnet Atomic Settlement',
          description: 'Cross-border liquidity pool transfer verified in Block #194829',
          timestamp: new Date(Date.now() - 3600000 * 24 + 4100).toISOString(),
          isCompleted: true,
          isCurrent: false,
          isFailed: false,
          txHash: '0x3c91a8e104f2d7a984bc19d678e0293847f9810427acde84792bce9812401f82'
        },
        {
          step: 'RECIPIENT_CREDITED',
          title: 'Recipient Credited via UPI',
          description: '₹29,225.00 credited instantly to State Bank of India account',
          timestamp: new Date(Date.now() - 3600000 * 24 + 4800).toISOString(),
          isCompleted: true,
          isCurrent: false,
          isFailed: false,
        }
      ],
      blockchainSettlement: {
        tokenSymbol: 'AUST',
        contractAddress: '0x5FbDB2315678afecb367f032d93F642f64180aa3',
        tokenAmount: '350.00 AUST',
        txHash: '0x3c91a8e104f2d7a984bc19d678e0293847f9810427acde84792bce9812401f82',
        blockNumber: 194829,
        network: 'Auto-UPI EVM Testnet (Chain 31337)',
        gasUsed: '42,108 Gas',
        settlementTimestamp: new Date(Date.now() - 3600000 * 24 + 4100).toISOString(),
        explorerUrl: 'https://testnet.auto-upi.io/tx/0x3c91a8e104f2d7a984bc19d678e0293847f9810427acde84792bce9812401f82'
      },
      createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
      updatedAt: new Date(Date.now() - 3600000 * 24 + 4800).toISOString(),
      settledAt: new Date(Date.now() - 3600000 * 24 + 4800).toISOString(),
    },
    {
      id: 'tx_upi_992811',
      referenceNumber: 'UPI-XB-8921821',
      userId: 'usr_auto_889210',
      beneficiaryId: 'ben_alex_gb',
      beneficiaryName: 'Alex Johnson',
      beneficiaryUpiId: 'alex.j@payuk',
      beneficiaryCountry: 'United Kingdom',
      beneficiaryFlag: '🇬🇧',
      senderBankAccountId: 'acc_chase_usd_01',
      senderBankName: 'JPMorgan Chase Bank',
      senderUpiId: 'aarav@autoupi',
      sourceCurrency: 'USD',
      sourceAmount: 600.00,
      targetCurrency: 'GBP',
      targetAmount: 472.80,
      exchangeRate: 0.788,
      fee: 2.00,
      feeCurrency: 'USD',
      status: 'RECIPIENT_CREDITED',
      purpose: 'SERVICES',
      note: 'UI Design consulting retainer',
      timeline: [
        {
          step: 'INITIATED',
          title: 'Payment Initiated',
          description: 'Payment authorized via biometric confirmation',
          timestamp: new Date(Date.now() - 3600000 * 72).toISOString(),
          isCompleted: true,
          isCurrent: false,
          isFailed: false,
        },
        {
          step: 'FX_LOCKED',
          title: 'FX Rate Guaranteed',
          description: 'Locked 1 USD = 0.788 GBP',
          timestamp: new Date(Date.now() - 3600000 * 72 + 1200).toISOString(),
          isCompleted: true,
          isCurrent: false,
          isFailed: false,
        },
        {
          step: 'RESERVE_LOCKED',
          title: 'Bank Reserve Escrow Locked',
          description: 'USD 600.00 locked in JPMorgan Chase custody vault',
          timestamp: new Date(Date.now() - 3600000 * 72 + 2100).toISOString(),
          isCompleted: true,
          isCurrent: false,
          isFailed: false,
        },
        {
          step: 'TOKEN_MINTED',
          title: 'Settlement Token Minted',
          description: '600.00 AUST minted on Auto-UPI EVM Testnet',
          timestamp: new Date(Date.now() - 3600000 * 72 + 3400).toISOString(),
          isCompleted: true,
          isCurrent: false,
          isFailed: false,
        },
        {
          step: 'BLOCKCHAIN_SETTLED',
          title: 'EVM Testnet Atomic Settlement',
          description: 'Settled in Block #194602',
          timestamp: new Date(Date.now() - 3600000 * 72 + 4200).toISOString(),
          isCompleted: true,
          isCurrent: false,
          isFailed: false,
        },
        {
          step: 'RECIPIENT_CREDITED',
          title: 'Recipient Credited via UK Faster Payments',
          description: '£472.80 credited instantly to Barclays Bank account',
          timestamp: new Date(Date.now() - 3600000 * 72 + 5100).toISOString(),
          isCompleted: true,
          isCurrent: false,
          isFailed: false,
        }
      ],
      createdAt: new Date(Date.now() - 3600000 * 72).toISOString(),
      updatedAt: new Date(Date.now() - 3600000 * 72 + 5100).toISOString(),
      settledAt: new Date(Date.now() - 3600000 * 72 + 5100).toISOString(),
    }
  ];

  public getMetrics(): AdminSystemMetrics {
    const totalTransactionsCount = this.transactions.length + 1842;
    const totalSettledVolumeUsd = this.transactions.reduce((sum, tx) => sum + tx.sourceAmount, 2489200);
    const activeReserveLiquidityUsd = 12500000;
    const mintedTokenSupplyAust = 8421000;
    const averageSettlementTimeSeconds = 3.8;

    return {
      totalSettledVolumeUsd,
      totalTransactionsCount,
      activeReserveLiquidityUsd,
      mintedTokenSupplyAust,
      averageSettlementTimeSeconds,
      systemHealth: 'HEALTHY',
      recentSettlementEvents: [
        {
          id: 'evt_101',
          timestamp: new Date(Date.now() - 120000).toISOString(),
          type: 'MINT',
          amountAust: 1500,
          corridor: 'USD -> INR',
          status: 'CONFIRMED',
          txHash: '0x71a...39f'
        },
        {
          id: 'evt_102',
          timestamp: new Date(Date.now() - 340000).toISOString(),
          type: 'RESERVE_LOCK',
          amountAust: 3200,
          corridor: 'EUR -> SGD',
          status: 'CONFIRMED',
          txHash: '0x99c...10a'
        },
        {
          id: 'evt_103',
          timestamp: new Date(Date.now() - 650000).toISOString(),
          type: 'DISPATCH',
          amountAust: 800,
          corridor: 'USD -> GBP',
          status: 'CONFIRMED',
          txHash: '0x22f...81e'
        }
      ],
      corridorVolumes: [
        { corridor: 'USD -> INR', volumeUsd: 1420000, percentage: 57 },
        { corridor: 'USD -> GBP', volumeUsd: 480000, percentage: 19 },
        { corridor: 'EUR -> SGD', volumeUsd: 350000, percentage: 14 },
        { corridor: 'USD -> EUR', volumeUsd: 239200, percentage: 10 },
      ]
    };
  }
}

export const db = new InMemoryDatabase();
