import { fxService } from '../src/services/fx';
import { feeEngine } from '../src/services/fee';
import { db } from '../src/db';

async function runTests() {
  console.log('🧪 Starting Part 4 Beneficiary, FX Engine, Fee Engine & Payment Creation Tests...\n');

  let passed = 0;
  let failed = 0;

  function assert(condition: boolean, testName: string) {
    if (condition) {
      console.log(`  ✅ PASS: ${testName}`);
      passed++;
    } else {
      console.error(`  ❌ FAIL: ${testName}`);
      failed++;
    }
  }

  // 1. Beneficiaries Data & Masking
  console.log('1. Testing Beneficiary Models & Masking...');
  const ben = db.beneficiaries[0];
  assert(ben.name === 'Priya Sharma', 'Beneficiary full name is preserved');
  assert(ben.accountNumberMasked.startsWith('••••'), 'Account number is safely masked');
  assert(ben.routingIdentifier === 'SBIN0004829', 'Routing identifier is stored');
  assert(ben.verificationState === 'VERIFIED', 'Verification state is present');

  // 2. Configurable Fee Engine
  console.log('\n2. Testing Configurable Fee Engine...');
  const defaultFee = feeEngine.calculateFee('USD', 'INR', 350, 83.50);
  assert(defaultFee.totalFees === 1.50, 'Standard USD fixed fee calculated correctly');
  assert(defaultFee.fxSpreadPercentage === 0.20, 'FX spread percentage is 0.20%');
  assert(defaultFee.effectiveRate < defaultFee.marketRate, 'Effective rate accounts for spread');

  // Corridor-specific fee override
  const inrFee = feeEngine.calculateFee('INR', 'USD', 10000, 0.01198);
  assert(inrFee.networkSettlementFee === 100, 'INR corridor fixed fee is ₹100');

  // 3. Authoritative FX Engine & Quote Generation
  console.log('\n3. Testing FX Engine & 30-Second Rate Lock...');
  const quote = fxService.createQuote('USD', 'INR', 350);
  assert(quote.quoteId.startsWith('quo_'), 'Quote ID generated by backend');
  assert(quote.sourceAmount === 350, 'Source amount matches');
  assert(quote.targetAmount > 25000, 'Destination amount calculated correctly');
  assert(quote.totalDebitAmount === 351.50, 'Total debit amount includes fees');
  assert(quote.expiresInSeconds === 30, 'Rate lock window is 30 seconds');
  assert(quote.estimatedSettlementTime === '~60 sec target', 'Estimated settlement time is ~60 sec target');

  // Quote Validation
  const validation = fxService.validateAndLockQuote(quote.quoteId);
  assert(validation.valid === true, 'Fresh quote validates successfully');

  // Expired quote test
  const expiredQuote = fxService.createQuote('USD', 'EUR', 100);
  expiredQuote.guaranteedUntil = new Date(Date.now() - 5000).toISOString();
  expiredQuote.isExpired = true;
  const expiredValidation = fxService.validateAndLockQuote(expiredQuote.quoteId);
  assert(expiredValidation.valid === false, 'Expired quote rejected by rate lock validator');

  console.log(`\n========================================`);
  console.log(`📊 Test Results: ${passed} Passed, ${failed} Failed`);
  console.log(`========================================\n`);

  if (failed > 0) {
    process.exit(1);
  }
}

runTests().catch((err) => {
  console.error('Test execution error:', err);
  process.exit(1);
});
